#!/usr/bin/env python3
"""
supabase_rls_check.py — Vérifie que le RLS est activé sur toutes les tables.
Analyse les fichiers de migration SQL pour détecter les tables sans RLS.

Usage : python scripts/supabase_rls_check.py [--fix]
  --fix : génère un fichier de migration correctif pour les tables sans RLS
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS_DIR = ROOT / "supabase" / "migrations"

GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
BOLD = "\033[1m"
RESET = "\033[0m"

# Tables système à ignorer
SYSTEM_TABLES = {"schema_migrations", "spatial_ref_sys", "_prisma_migrations"}


def extract_created_tables(sql: str) -> set[str]:
    pattern = re.compile(
        r"CREATE TABLE(?:\s+IF NOT EXISTS)?\s+(?:public\.)?(\w+)",
        re.IGNORECASE,
    )
    return {m.group(1).lower() for m in pattern.finditer(sql)}


def extract_rls_enabled_tables(sql: str) -> set[str]:
    pattern = re.compile(
        r"ALTER TABLE\s+(?:public\.)?(\w+)\s+ENABLE ROW LEVEL SECURITY",
        re.IGNORECASE,
    )
    return {m.group(1).lower() for m in pattern.finditer(sql)}


def extract_rls_policies(sql: str) -> dict[str, list[str]]:
    """Retourne un dict {table: [policy_names]}"""
    pattern = re.compile(
        r"CREATE POLICY\s+\S+\s+ON\s+(?:public\.)?(\w+)",
        re.IGNORECASE,
    )
    result: dict[str, list[str]] = {}
    for m in pattern.finditer(sql):
        table = m.group(1).lower()
        result.setdefault(table, []).append(m.group(0)[:60])
    return result


def analyze_migrations() -> tuple[set[str], set[str], dict[str, list[str]]]:
    if not MIGRATIONS_DIR.exists():
        return set(), set(), {}

    all_tables: set[str] = set()
    rls_enabled: set[str] = set()
    all_policies: dict[str, list[str]] = {}

    for sql_file in sorted(MIGRATIONS_DIR.glob("*.sql")):
        content = sql_file.read_text(encoding="utf-8", errors="ignore")
        all_tables |= extract_created_tables(content)
        rls_enabled |= extract_rls_enabled_tables(content)
        for table, policies in extract_rls_policies(content).items():
            all_policies.setdefault(table, []).extend(policies)

    # Retirer les tables système
    all_tables -= SYSTEM_TABLES
    return all_tables, rls_enabled, all_policies


def generate_fix_migration(tables_without_rls: set[str]) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    filename = MIGRATIONS_DIR / f"{timestamp}_enable_rls_missing_tables.sql"
    lines = ["-- Auto-generated by supabase_rls_check.py", "-- Activates RLS on tables missing it", ""]
    for table in sorted(tables_without_rls):
        lines.append(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY;")
        lines.append(f"-- TODO: Ajouter des policies pour {table}")
        lines.append(f"-- CREATE POLICY \"select_{table}\" ON public.{table} FOR SELECT USING (auth.uid() IS NOT NULL);")
        lines.append("")
    filename.write_text("\n".join(lines), encoding="utf-8")
    return filename


def main() -> None:
    parser = argparse.ArgumentParser(description="Vérifie le RLS Supabase")
    parser.add_argument("--fix", action="store_true",
                        help="Générer une migration correctrice")
    args = parser.parse_args()

    if not MIGRATIONS_DIR.exists():
        print(f"{YELLOW}⚠ Pas de dossier supabase/migrations trouvé.{RESET}")
        sys.exit(0)

    all_tables, rls_enabled, policies = analyze_migrations()

    if not all_tables:
        print(f"{YELLOW}Aucune table CREATE TABLE trouvée dans les migrations.{RESET}")
        sys.exit(0)

    tables_without_rls = all_tables - rls_enabled
    tables_without_policies = {t for t in rls_enabled if t not in policies}

    print(f"\n{BOLD}=== Rapport RLS Supabase ==={RESET}\n")
    print(f"  Tables détectées       : {len(all_tables)}")
    print(f"  Tables avec RLS activé : {len(rls_enabled)}")
    print(f"  Tables SANS RLS        : {len(tables_without_rls)}")
    print(f"  Tables RLS sans policy : {len(tables_without_policies)}\n")

    if tables_without_rls:
        print(f"{RED}Tables sans RLS :{RESET}")
        for t in sorted(tables_without_rls):
            print(f"  ✗ {t}")

    if tables_without_policies:
        print(f"\n{YELLOW}Tables avec RLS mais sans policy (accès bloqué) :{RESET}")
        for t in sorted(tables_without_policies):
            print(f"  ⚠ {t}")

    if rls_enabled:
        print(f"\n{GREEN}Tables avec RLS :{RESET}")
        for t in sorted(rls_enabled):
            n = len(policies.get(t, []))
            print(f"  ✓ {t} ({n} polic{'ies' if n != 1 else 'y'})")

    if tables_without_rls and args.fix:
        fix_file = generate_fix_migration(tables_without_rls)
        print(f"\n{GREEN}Migration générée : {fix_file.relative_to(ROOT)}{RESET}")
        print("Vérifier et compléter les policies avant d'appliquer.")

    if tables_without_rls:
        print(f"\n{RED}ECHEC — {len(tables_without_rls)} table(s) sans RLS.{RESET}")
        if not args.fix:
            print(f"Relancer avec --fix pour générer une migration correctrice.")
        sys.exit(1)
    else:
        print(f"\n{GREEN}OK — RLS activé sur toutes les tables.{RESET}")
